services:
  backend:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@database:5432/postgram_db
      - JWT_SECRET=change-this-secret

  database:
    image: postgres:16-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgram_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
